# SwiftLint Configuration for ScreenMacros

# Paths to include
included:
  - Sources
  - Tests

# Paths to exclude
excluded:
  - Example
  - .build
  - Package.swift

# Disabled rules
disabled_rules:
  - trailing_comma
  - opening_brace
  - identifier_name
  - type_name
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - modifier_order
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - yoda_condition

# Rule configurations
line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

file_length:
  warning: 1000
  error: 1500
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

# Custom rules
custom_rules:
  no_print:
    name: "No print statements"
    regex: "\\bprint\\s*\\("
    message: "Use os_log or a logging framework instead of print"
    severity: warning
